license="GNU GPLv3"
modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/klangzwang/WitherUtils/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/witherutils"
logoFile="witherutils.png"
credits=""
authors="klangzwang, helgenius"

[[mods]]
	modId="witherutils"
    version="${mod_version}"
	displayName="WitherUtils"
	description='''
When working at Technical Ideas '''

[[dependencies.witherutils]]
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.witherutils]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.witherutils]]
    modId="jei"
    type="optional"
    versionRange="[19.0.0,)"
    ordering="NONE"
    side="BOTH"

[[accessTransformers]]
	file="META-INF/accesstransformer.cfg"

[[mixins]]
    config = "mixins.witherutils.json"