package geni.witherutils.base.common.init;

import geni.witherutils.api.lib.Names;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class WUTSounds {

	public static final DeferredRegister<SoundEvent> SOUND_TYPES = DeferredRegister.create(Registries.SOUND_EVENT, Names.MODID);

	public static final DeferredHolder<SoundEvent, SoundEvent> DRYHEAD_DEATH = SOUND_TYPES.register("dryhead_death", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "dryhead_death")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DRYHEAD_INCOMING = SOUND_TYPES.register("dryhead_incoming", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "dryhead_incoming")));
	public static final DeferredHolder<SoundEvent, SoundEvent> LASER0 = SOUND_TYPES.register("laser0", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "laser0")));
	public static final DeferredHolder<SoundEvent, SoundEvent> LASER1 = SOUND_TYPES.register("laser1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "laser1")));
	public static final DeferredHolder<SoundEvent, SoundEvent> LASER2 = SOUND_TYPES.register("laser2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "laser2")));
	public static final DeferredHolder<SoundEvent, SoundEvent> ENGINELOOP = SOUND_TYPES.register("engineloop", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "engineloop")));
	public static final DeferredHolder<SoundEvent, SoundEvent> ENGINESTART = SOUND_TYPES.register("enginestart", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "enginestart")));
	public static final DeferredHolder<SoundEvent, SoundEvent> ENGINESTOP = SOUND_TYPES.register("enginestop", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "enginestop")));
	public static final DeferredHolder<SoundEvent, SoundEvent> NOISE = SOUND_TYPES.register("noise", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "noise")));
	public static final DeferredHolder<SoundEvent, SoundEvent> STARTUP = SOUND_TYPES.register("startup", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "startup")));
	public static final DeferredHolder<SoundEvent, SoundEvent> METALPLACE = SOUND_TYPES.register("metalplace", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "metalplace")));
	public static final DeferredHolder<SoundEvent, SoundEvent> METALBREAK = SOUND_TYPES.register("metalbreak", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "metalbreak")));
	public static final DeferredHolder<SoundEvent, SoundEvent> MINIONATTACK1 = SOUND_TYPES.register("minionattack1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "minionattack1")));
	public static final DeferredHolder<SoundEvent, SoundEvent> MINIONCAST = SOUND_TYPES.register("minioncast", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "minioncast")));
	public static final DeferredHolder<SoundEvent, SoundEvent> MINIONHURT = SOUND_TYPES.register("minionhurt", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "minionhurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> CHARGETICK = SOUND_TYPES.register("chargetick", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "chargetick")));
	public static final DeferredHolder<SoundEvent, SoundEvent> CHARGESOULS = SOUND_TYPES.register("chargesouls", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "chargesouls")));
	public static final DeferredHolder<SoundEvent, SoundEvent> WOODPOOL = SOUND_TYPES.register("woodpool", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "woodpool")));
	public static final DeferredHolder<SoundEvent, SoundEvent> WORMBIP = SOUND_TYPES.register("wormbip", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "wormbip")));
	public static final DeferredHolder<SoundEvent, SoundEvent> SCREAM = SOUND_TYPES.register("scream", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "scream")));
	public static final DeferredHolder<SoundEvent, SoundEvent> CUTTER = SOUND_TYPES.register("cutter", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "cutter")));
	public static final DeferredHolder<SoundEvent, SoundEvent> BURNBG = SOUND_TYPES.register("burnbg", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "burnbg")));
	public static final DeferredHolder<SoundEvent, SoundEvent> GASOLINE = SOUND_TYPES.register("gasoline", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "gasoline")));
	public static final DeferredHolder<SoundEvent, SoundEvent> GASON = SOUND_TYPES.register("gason", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "gason")));
	public static final DeferredHolder<SoundEvent, SoundEvent> GASOFF = SOUND_TYPES.register("gasoff", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "gasoff")));
	public static final DeferredHolder<SoundEvent, SoundEvent> PICKPLICK = SOUND_TYPES.register("pickplick", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "pickplick")));
	public static final DeferredHolder<SoundEvent, SoundEvent> PICKRIB = SOUND_TYPES.register("pickrib", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "pickrib")));
	public static final DeferredHolder<SoundEvent, SoundEvent> PICKSHEE = SOUND_TYPES.register("pickshee", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "pickshee")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FEAR = SOUND_TYPES.register("fear", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "fear")));
	public static final DeferredHolder<SoundEvent, SoundEvent> SLOT = SOUND_TYPES.register("slot", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "slot")));
	public static final DeferredHolder<SoundEvent, SoundEvent> REACT = SOUND_TYPES.register("react", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "react")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GENERATOR = SOUND_TYPES.register("generator", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "generator")));
    public static final DeferredHolder<SoundEvent, SoundEvent> PLACEBOOMONE = SOUND_TYPES.register("place_boom1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "place_boom1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> PLACEBOOMTWO = SOUND_TYPES.register("place_boom2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "place_boom2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> PLACESSSHHHH = SOUND_TYPES.register("place_sssh", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "place_sssh")));
    public static final DeferredHolder<SoundEvent, SoundEvent> HAMMERHIT = SOUND_TYPES.register("hammerhit", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "hammerhit")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SWOOSH = SOUND_TYPES.register("swoosh", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "swoosh")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WRINKLYAMBIENT = SOUND_TYPES.register("wrinkly_ambient", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "wrinkly_ambient")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WRINKLYDEATH = SOUND_TYPES.register("wrinkly_death", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "wrinkly_death")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WRINKLYSPAWN = SOUND_TYPES.register("wrinkly_spawn", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "wrinkly_spawn")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WRINKLYDISTANT = SOUND_TYPES.register("wrinkly_distant", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "wrinkly_distant")));
    public static final DeferredHolder<SoundEvent, SoundEvent> ELECTRO = SOUND_TYPES.register("electro", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "electro")));
    public static final DeferredHolder<SoundEvent, SoundEvent> ELECTRODISTANT = SOUND_TYPES.register("electro_distant", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "electro_distant")));
    public static final DeferredHolder<SoundEvent, SoundEvent> VISIONON = SOUND_TYPES.register("nightvisionon", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "nightvisionon")));
    public static final DeferredHolder<SoundEvent, SoundEvent> VISIONOFF = SOUND_TYPES.register("nightvisionoff", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "nightvisionoff")));
    public static final DeferredHolder<SoundEvent, SoundEvent> JUMP = SOUND_TYPES.register("jumping", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "jumping")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WINGS_FLAP = SOUND_TYPES.register("wingsflap", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "wingsflap")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WINGS_TAKEOFF = SOUND_TYPES.register("wingstakeoff", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "wingstakeoff")));
    public static final DeferredHolder<SoundEvent, SoundEvent> BUZZ = SOUND_TYPES.register("buzz", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "buzz")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SHIELDHIT = SOUND_TYPES.register("shieldhit", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "shieldhit")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LOSTPOWER = SOUND_TYPES.register("lostpower", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "lostpower")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WATERHIT = SOUND_TYPES.register("waterhit", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "waterhit")));
    public static final DeferredHolder<SoundEvent, SoundEvent> RODSPOOL = SOUND_TYPES.register("rodspool", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "rodspool")));
    public static final DeferredHolder<SoundEvent, SoundEvent> FILTERMOB = SOUND_TYPES.register("filtermob", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "filtermob")));
    public static final DeferredHolder<SoundEvent, SoundEvent> FILTERMOBCLEAR = SOUND_TYPES.register("filtermobclear", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "filtermobclear")));
    public static final DeferredHolder<SoundEvent, SoundEvent> BUCKET = SOUND_TYPES.register("bucket", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "bucket")));
    public static final DeferredHolder<SoundEvent, SoundEvent> HANGARDOOROPEN = SOUND_TYPES.register("hangardooropen", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "hangardooropen")));
    public static final DeferredHolder<SoundEvent, SoundEvent> HANGARDOORCLOSE = SOUND_TYPES.register("hangardoorclose", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "hangardoorclose")));
    public static final DeferredHolder<SoundEvent, SoundEvent> HANGARDOORFINISHED = SOUND_TYPES.register("hangardoorfinished", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(Names.MODID, "hangardoorfinished")));
}
